# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2
  
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  one:
    docker:
      - image: cimg/ruby:2.6.8
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    
    steps: 
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
      
  two:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    
    steps: 
      - checkout
      - run: echo "A more familiar hii"
      - attach_workspace:
          at: my_wprkspace
      - run: 
        if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
          echo "It worked!";
        else
          echo "Nope!"; exit 1
        fi
          
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            -one
